shop/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views

from shoppe import settings
from .views import *

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('shop/', Shop.as_view(), name='shop'),
    path('product/<int:product_id>', ProductView.as_view(), name='product_page'),
    path('privacy-policy/', TermsOfServices.as_view(), name='privacy'),
    path('cart/', CartView.as_view(), name='cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order/<int:order_id>/', OrderView.as_view(), name='order'),
    path('contact-us/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),

    #user
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('account/', AccountView.as_view(), name='account'),
    path('verify/<auth_token>/', verify, name='verify'),

    #passwords
    path('password_reset/', ChangePasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', ChangePasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', ChangePasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', ChangePasswordResetComplete.as_view(), name='password_reset_complete'),

    #favorites
    path('favorites/add/', add_to_favorites, name='add_fav'),
    path('favorites/remove/', remove_from_favorites, name='remove_fav'),
    path('favorites/api/', favorites_api, name='api'),

    #cart
    path('cart-options/add', add_to_cart, name='add_cart'),
    path('cart-options/remove', remove_from_cart, name='remove_cart'),
    path('cart-options/clear', clear_cart, name='clear_cart'),
    path('cart-options/sale', sale_cart, name='sale_cart'),
    path('cart-options/json', cart_json, name='json_cart'),

    #order
    path('create-order/', create_order, name='create_order'),

    #email
    path('email-news/add/', email_news, name='email_news')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppe/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from rest_framework import routers

from shop.views import *
from shop.view_api import *
from shoppe import settings

router = routers.SimpleRouter()
router.register(r'products', ProductAPI)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),

    # api
    path('api/v1/', include(router.urls)),
    path('api/v1/orders/', OrderListAPI.as_view()),
    path('api/v1/orders/<int:pk>/', OrderDetailAPI.as_view()),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = pageNotFound

shop/models.py
from django.contrib import admin
from django.core.mail import EmailMessage
from django.db import models
from django.db.models.signals import *
from django.dispatch import receiver
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField

from .utils import EmailThread
from .validators import *


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_verify = models.BooleanField(default=False)
    auth_token = models.CharField(max_length=255, unique=True)
    user_json = models.JSONField(null=False, default={}, blank=True)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name



class Product(models.Model):
    sku = models.CharField(max_length=20, unique=True)
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=7, decimal_places=2, validators=[validate_positive])
    quantity = models.PositiveIntegerField()
    sale = models.PositiveSmallIntegerField(default=0)
    description = models.TextField(blank=True)
    category = models.ForeignKey('Category', on_delete=models.PROTECT, default='0')

    #m2m fields
    attribute_SET = models.ManyToManyField(
        'Attribute',
        through='AttributeValues',
        through_fields=('product', 'attribute'),
    )

    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_page', kwargs={'product_id': self.id})

    def image_tag(self):
        d = self.photo_set.first()
        return d.image_tag() if d else mark_safe('<p>NONE</p>')
    image_tag.short_description = 'Image'



@receiver(post_save, sender=Product)
def send_email_news(sender, instance, created, **kwargs):
    if instance.is_published:
        emails = EmailNews.objects.all()
        subject = 'New Product'
        message = f'The new {instance.title} is finally available! \n\nhttp://127.0.0.1:8000{instance.get_absolute_url()}'
        recipient_list = [x.email for x in emails]
        EmailThread(subject, message, recipient_list).start()

class Attribute(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class AttributeValues(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    attribute = models.ForeignKey('Attribute', on_delete=models.CASCADE)

    value_text = models.CharField(max_length=128, default=' ')


class Photo(models.Model):
    product = models.ForeignKey('Product', on_delete=models.PROTECT)
    image = models.ImageField(upload_to="img/%Y/%m/%d")
    index = models.PositiveSmallIntegerField(default=0, blank=False, null=False, db_index=True)

    class Meta:
        ordering = ['index']

    def image_tag(self):
        return mark_safe('<img src="%s" height="100" />' % (self.image.url))
    image_tag.short_description = 'Image'


class Review(models.Model):
    text = models.TextField(max_length=255)
    star_rating = models.PositiveSmallIntegerField(validators=[starValid], default=1)
    name = models.CharField(max_length=255, null=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)
    product = models.ForeignKey('Product', on_delete=models.CASCADE, null=True)

    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.product} - {self.name}'

class Order(models.Model):
    status_var = [
        ('New', 'New'),
        ('In processing', 'In processing'),
        ('Confirmed', 'Confirmed'),
        ('Delivered', 'Delivered'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    ]

    status = models.CharField(max_length=255, choices=status_var, default='New')
    shipping_price = models.DecimalField(max_digits=5, decimal_places=2, validators=[validate_positive], default=0)
    sale = models.ForeignKey('Coupon', on_delete=models.PROTECT, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT, blank=True, null=True)
    payment_method = models.CharField(max_length=255)
    payment_status = models.BooleanField(default=False)

    time_create = models.DateTimeField(auto_now_add=True)

    #address
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    company_name = models.CharField(max_length=255, blank=True)
    country = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    postcode = models.PositiveSmallIntegerField()
    town = models.CharField(max_length=255)
    phone = PhoneNumberField()
    email = models.EmailField()

    order_notes = models.TextField(blank=True)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('order', kwargs={'order_id': self.id})

class OrderList(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.PROTECT)
    quantity = models.PositiveSmallIntegerField(default=1)
    new_quantity = models.PositiveSmallIntegerField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[validate_positive], default=0)

    @admin.display(description='max count')
    def max_quantity(self):
        return self.product.quantity + self.quantity

    @admin.display(description='image')
    def image_product(self):
        return self.product.photo_set.first().image_tag()

    def __str__(self):
        return str(self.order)


@receiver(post_save, sender=OrderList)
def my_handler2(sender, instance, **kwargs):
    print(OrderList.objects.filter(id=instance.id))
    OrderList.objects.filter(id=instance.id).update(quantity = instance.new_quantity, new_quantity = 0)

@receiver(post_save, sender=OrderList)
def my_handler2(sender, instance, created, **kwargs):
    if created:
        d = Product.objects.get(id=instance.product_id)
        d.quantity -= instance.quantity
        d.save()


@receiver(post_delete, sender=OrderList)
def my_handler3(sender, instance, **kwargs):
    d = Product.objects.get(id=instance.product_id)
    d.quantity += instance.quantity
    d.save()


class Coupon(models.Model):
    code = models.CharField(max_length=25, unique=True)
    sale_percent = models.PositiveSmallIntegerField(validators=[sale_validate])
    max_uses = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return self.code


class EmailNews(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email


class PreViewPhoto(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="img/%Y/%m/%d")
    is_published = models.BooleanField(default=False)

    def __str__(self):
        return self.product.title

    def get_absolute_url(self):
        return self.product.get_absolute_url()

shop/templates/shop/about.html
{% extends 'shop/base.html' %}
{% load static %}

{% block css_styles %}
<link rel="stylesheet" href="{% static 'shop/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'shop/css/about.css' %}">
{% endblock %}

{% block header %}
<header class="header">
    <div class="header-wrapper header-border">
        <div class="header-logo">
            <a href="{% url 'home' %}" class="header-logo-link">
                <h1 class="header-logo-link-title">
                    SHOPPE
                </h1>
            </a>
        </div>
        <div class="header_burger">
            <span></span>
        </div>
        <div class="header-menu">
            <div class="header-menu-items">
                <a href="{% url 'shop' %}" class="header-menu-link-text">
                    Shop
                </a>
                <a href="{% url 'about' %}" class="header-menu-link-text flicking">
                    Our Story
                </a>
            </div>
            <span>|</span>
            <div class="header-menu-items">
                <a href="{% url 'cart' %}" class="header-menu-link-icon">
                    <img src="{% static 'shop/img/svg/header/icon-shopping.svg' %}" alt="shopping">
                    <span class="icon-label">Cart</span>
                </a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'account' %}" class="header-menu-link-icon">
                        <img src="{% static 'shop/img/svg/header/icon-user.svg' %}" alt="user">
                        <span class="icon-label">My Account</span>
                    </a>
                {% else %}
                    <a href="{% url 'login' %}" class="header-menu-link-icon">
                        <img src="{% static 'shop/img/svg/header/icon-user.svg' %}" alt="user">
                        <span class="icon-label">My Account</span>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block main %}
<main class="main">
    <div class="about-wrap">
        <h1 class="title-wrap">
            About
        </h1>
        <p class="about-desc">
            This site was made solo by a 17 years old guy. This site is not a real online store, but just one of the portfolio projects. The site has many different and interesting features and capabilities. You can create an order, view the products you like, filter and add comments under the product.
        </p>
    </div>
</main>
{% endblock %}

shop/templates/shop/account.html
{% extends 'shop/user_flick_header.html' %}
{% load static %}
{% load shop_tags %}

{% block css_styles %}
<link rel="stylesheet" href="{% static 'shop/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'shop/css/account.css' %}">
{% endblock %}


{% block main %}
<main class="main">
    <h1 class="title-wrap">
        My Account
    </h1>

    <section class="account-tabs">
        <!-- Tab links -->
        <div class="tab">
            <button class="tablinks" id="defaultOpen" onclick="openCity(event, 'Dashboard')">Dashboard</button>
            <button class="tablinks" onclick="openCity(event, 'Orders')">Orders</button>
            <button class="tablinks" onclick="openCity(event, 'Liked')">Liked</button>
            <button class="tablinks" onclick="openCity(event, 'Account details')">Account details</button>
            <a href="{% url 'logout' %}" class="tablinks">Logout</a>
        </div>

        <!-- Tab content -->
        <div id="Dashboard" class="tabcontent">
            <p class="dashboard-p">Hello {{ user.first_name }} (not {{ user.first_name }}? <a href="{% url 'logout' %}" class="dashboard-link">Log out</a>)</p>
<!--            <p class="dashboard-p">From your account dashboard you can view your <a href="#!" class="dashboard-link">recent orders</a>, manage your <a href="#!" class="dashboard-link">shipping and billing addresses</a>, and edit your <a href="#!" class="dashboard-link">password and account details.</a></p>-->
        </div>

        <div id="Orders" class="tabcontent">
            <!-- if nothing -->
            {% if orders %}
                <table class="account-table">
                    <tbody>
                        <tr>
                            <th>ORDER NUMBER</th>
                            <th>DATE</th>
                            <th>STATUS</th>
                            <th>TOTAL</th>
                            <th>ACTIONS</th>
                        </tr>
                        {% for i in orders %}
                            <tr>
                                <td>{{i.id}}</td>
                                <td>{{i.time_create|date:"j M, Y" }}</td>
                                <td>{{i.status}}</td>
                                <td>$ {{i.orderlist_set.all|sum_subtotal|add:i.shipping_price}}</td>
                                <td><a href="{{ i.get_absolute_url }}" class="account-table-link">View Order</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <div class="account-message">
                    <p class="account-message-text">
                        No order has been made yet.
                    </p>
                    <a href="{% url 'shop' %}" class="account-message-link">
                        BROWSE PRODUCT
                    </a>
                </div>
            {% endif %}
        </div>

        <div id="Liked" class="tabcontent">

            {% if liked %}
                <div class="liked-items">
                {% for i in liked %}
                    <div class="liked-item">
                        <div class="item-pic-wrap">
                            <img src="{{ i.photo_set.first.image.url }}" alt="image" class="item-pic">
                        </div>
                        <div class="item-info">
                            <div>
                                <p>
                                    {{ i.title }}
                                </p>
                                <p>
                                    $ {{ i.price }}
                                </p>
                            </div>
                            <a href="{{ i.get_absolute_url }}">View Product</a>
                        </div>
                    </div>
                {% endfor %}
                </div>
            {% else %}
                <div class="account-message">
                    <p class="account-message-text">
                        You don't have any products you like
                    </p>
                    <a href="{% url 'shop' %}" class="account-message-link">
                        BROWSE PRODUCT
                    </a>
                </div>
            {% endif %}
        </div>

        <div id="Account details" class="tabcontent">
            <div class="account-details-wrap">
                <h2 class="account-details-title">
                    Account details
                </h2>
                <form action="{% url 'account' %}" class="account-details-form" method="post">
                    {% csrf_token %}
                    <div class="input-wrap">
                        {{ user_form.first_name }}
                    </div>
                    <div class="input-wrap">
                        {{ user_form.last_name }}
                    </div>
                    <div class="input-wrap">
                        {{ user_form.username }}
                        <div class="form-errors">
                            {{ user_form.username.errors }}
                        </div>
                    </div>
                    <div class="input-wrap">
                        {{ user_form.email }}
                    </div>

                    <button type="submit" class="sign-in_form-submit">SAVE CHANGES</button>

                </form>
            </div>
        </div>

    </section>
</main>
{% endblock %}

{% block js_scripts %}
<script src="{% static 'shop/js/tabs.js' %}"></script>
{% endblock %}

shop/templates/shop/cart_flick_header.html
{% extends 'shop/base.html' %}
{% load static %}

{% block header %}
<header class="header">
    <div class="header-wrapper header-border">
        <div class="header-logo">
            <a href="{% url 'home' %}" class="header-logo-link">
                <h1 class="header-logo-link-title">
                    SHOPPE
                </h1>
            </a>
        </div>
        <div class="header_burger">
            <span></span>
        </div>
        <div class="header-menu">
            <div class="header-menu-items">
                <a href="{% url 'shop' %}" class="header-menu-link-text">
                    Shop
                </a>
                <a href="{% url 'about' %}" class="header-menu-link-text">
                    Our Story
                </a>
            </div>
            <span>|</span>
            <div class="header-menu-items">
                <a href="{% url 'cart' %}" class="header-menu-link-icon flicking">
                    <img src="{% static 'shop/img/svg/header/icon-shopping.svg' %}" alt="shopping">
                    <span class="icon-label">Cart</span>
                </a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'account' %}" class="header-menu-link-icon">
                        <img src="{% static 'shop/img/svg/header/icon-user.svg' %}" alt="user">
                        <span class="icon-label">My Account</span>
                    </a>
                {% else %}
                    <a href="{% url 'login' %}" class="header-menu-link-icon">
                        <img src="{% static 'shop/img/svg/header/icon-user.svg' %}" alt="user">
                        <span class="icon-label">My Account</span>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
</header>
{% endblock %}

shop/templates/shop/error.html
{% extends 'shop/base.html' %}

{% block css_styles %}
<link type="text/css" href="{% static 'shop/css/styles.css' %}" rel="stylesheet">
<link type="text/css" href="{% static 'shop/css/product_styles.css' %}" rel="stylesheet">
{% endblock %}


{% block main %}
<main class="main">
    <div class="error">
        <h2 class="error-title">
            404 ERROR
        </h2>
        <p class="error-text">
            This page not found;
            back to home and start again
        </p>
        <a href="{% url 'home' %}" class="error-link">
            <div class="error-link-button">
                HOMEPAGE
            </div>
        </a>
    </div>
</main>
{% endblock %}

shop/templates/shop/order.html
{% extends 'shop/base.html' %}
{% load static %}
{% load shop_tags %}

{% block css_styles %}
<link type="text/css" href="{% static 'shop/css/styles.css' %}" rel="stylesheet">
<link type="text/css" href="{% static 'shop/css/order.css' %}" rel="stylesheet">
{% endblock %}


{% block main %}
<main class="main">
    {% if can_view %}
        <section class="messages">
            <div class="added-cart message active-msg" id="yes-msg">
                <div class="first-added">
                    <img src="{% static 'shop/img/svg/main/messages/yes-icon.svg' %}" alt="yes" class="added-icon-message">
                    <p class="added-cart-message-text">
                        We’ve received your order
                    </p>
                </div>
            </div>
        </section>
        <div class="order-wrap">
            <div class="order-details">
                <h2 class="order-title">
                    Order Details
                </h2>
                <div class="order-details-wrap">
                    <div class="order-details-info">
                        <div class="order-details-info-wrap">
                            <div class="order-details-info-title">
                                ORDER NUMBER
                            </div>
                            <div class="order-details-info-desc">
                                {{ order.id }}
                            </div>
                        </div>
                        <div class="order-details-info-wrap">
                            <div class="order-details-info-title">
                                EMAIL
                            </div>
                            <div class="order-details-info-desc">
                                {{ order.email }}
                            </div>
                        </div>
                        <div class="order-details-info-wrap">
                            <div class="order-details-info-title">
                                CONTACT NUMBER
                            </div>
                            <div class="order-details-info-desc">
                                {{ order.phone }}
                            </div>
                        </div>
                        <div class="order-details-info-wrap">
                            <div class="order-details-info-title">
                                ORDER DATE
                            </div>
                            <div class="order-details-info-desc">
                                {{ order.time_create }}
                            </div>
                        </div>
                    </div>
                    <div class="order-details-info">
                        <div class="order-details-info-wrap">
                            <div class="order-details-info-title">
                                ORDER STATUS
                            </div>
                            <div class="order-details-info-desc">
                                {{ order.status }}
                            </div>
                        </div>
                        <div class="order-details-info-wrap">
                            <div class="order-details-info-title">
                                DELIVERY OPTIONS
                            </div>
                            <div class="order-details-info-desc">
                                Standard delivery
                            </div>
                        </div>
                        <div class="order-details-info-wrap">
                            <div class="order-details-info-title">
                                DELIVERY ADDRESS
                            </div>
                            <div class="order-details-info-desc">
                                {{order.country}} {{order.street}} {{order.postcode}} {{order.town}}
                            </div>
                        </div>
                        <div class="order-details-info-wrap">
                            <div class="order-details-info-title">
                                PAYMENT
                            </div>
                            <div class="order-details-info-desc">
                                {% if order.payment_status %}
                                    <i class="fa-sharp fa-solid fa-circle-check"></i> {{ order.payment_method }}
                                {% else %}
                                    <i class="fa-solid fa-circle-xmark"></i> {{ order.payment_method }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="order-summary">
                <h2 class="order-title">
                    Order Summary
                </h2>
                <div class="order-summary-info">
                    <div class="order-summary-info_header">
                        <div>
                            PRODUCT
                        </div>
                        <div>
                            TOTAL
                        </div>
                    </div>
                    <div class="order-summary-info_body">
                        {% for i in order.orderlist_set.all %}
                            <div class="order-summary-info_row">
                                <div>
                                    {{ i.product.title }}
                                </div>
                                <div>
                                     {{i.quantity}} x $ {{ i.price }}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="order-summary-info_last-items">
                        <div class="order-summary-last-items-info_row">
                            <div>
                                SUBTOTAL
                            </div>
                            <div>
                                $ {{ order.orderlist_set.all|sum_subtotal }}
                            </div>
                        </div>
                        {% if order.sale %}
                            <div class="order-summary-last-items-info_row">
                                <div>
                                    SALE (-{{order.sale.sale_percent}}%)
                                </div>
                                <div style="color: rgb(210, 0, 0);">
                                    - $ {{ order.orderlist_set.all|sum_subtotal|sale:order.sale.sale_percent}}
                                </div>
                            </div>
                        {% endif %}
                        <div class="order-summary-last-items-info_row">
                            <div>
                                SHIPPING
                            </div>
                            <div>
                                $ {{ order.shipping_price }}
                            </div>
                        </div>
                    </div>
                    <div class="order-summary-info_footer">
                        <div class="order-summary-info_footer-row">
                            <div>
                                TOTAL
                            </div>
                            {% if request.session.cart|get_item:'sale' %}
                                <div>
                                    $ {{ order.orderlist_set.all|sum_subtotal|with_sale:order.sale.sale_percent|add:order.shipping_price }}
                                </div>
                            {% else %}
                                 <div>
                                    $ {{ order.orderlist_set.all|sum_subtotal|add:order.shipping_price }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="order-nothing">
            <h2 class="order-nothing-title">
                ERROR
            </h2>
            <p class="order-nothing-text">
                You have been denied viewing this order
            </p>
            <a href="{% url 'home' %}" class="order-nothing-link">
                <div class="order-nothing-link-button">
                    HOMEPAGE
                </div>
            </a>
        </div>
    {% endif %}
</main>
{% endblock %}

{% block js_scripts %}
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="{% static 'shop/js/messageOrder.js' %}"></script>
{% endblock %}

shop/templates/shop/reset_password.html
{% extends 'shop/base.html' %}
{% load static %}

{% block css_styles %}
<link rel="stylesheet" href="{% static 'shop/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'shop/css/resetpassword.css' %}">
{% endblock %}


{% block main %}
<main class="main">
    <div class="reset_password">
        <h1 class="reset-title">
            Have you Forgotten Your Password ?
        </h1>
        <p class="reset-desc">
            If you've forgotten your password, enter your e-mail address and we'll send you an e-mail
        </p>
        <form class="reset-password_form" method="post">
            {% csrf_token %}
            {{form.email}}
            <button type="submit" class="form-button">RESET PASSWORD</button>
        </form>
    </div>
</main>
{% endblock %}

shop/templates/shop/reset_password_done.html
{% extends 'shop/base.html' %}
{% load static %}

{% block css_styles %}
<link rel="stylesheet" href="{% static 'shop/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'shop/css/resetpassword.css' %}">
{% endblock %}

{% block main%}
<main class="main">
    <div class="reset_password">
        <h1 class="reset-title">
            Password reset sent
        </h1>
        <p class="reset-desc">
            We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
        </p>
        <p class="reset-desc">
            If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
        </p>
    </div>
</main>
{% endblock %}